// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osuryrzyyhkywxrjeyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdXJ5cnp5eWhreXd4cmpleWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTA2NzksImV4cCI6MjA3NDQ2NjY3OX0.9-vcP36BlsqEg3VXtl_a9N8HdZffw2pciFc20UiznJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});